export interface Village {
  slug: string;
  name: string;
  scheme: string;
  zone: string;
  lat: number;
  lng: number;
  taluka: string;
  centerSurvey?: number;
  totalSurveysApprox?: number;
}

export const VILLAGES: Village[] = [
  // `scheme` must agree with the published cadastre in
  // public/data/search_index.json (the ground truth the map and the
  // /survey/[village]/[surveyNo] pages are generated from).
  // Coordinates are calibrated to Survey of India and GTPUD statutory boundaries.
  { 
    slug: 'ambli', 
    name: 'Ambli', 
    scheme: 'TP 1', 
    zone: 'Residential & Knowledge',
    lat: 22.2421,
    lng: 72.2314,
    taluka: 'Dholera',
    centerSurvey: 38,
    totalSurveysApprox: 1850,
  },
  { 
    slug: 'bavaliyari', 
    name: 'Bavaliyari', 
    scheme: 'TP 5 / TP 6', 
    zone: 'Expressway & Logistics',
    lat: 22.0853,
    lng: 72.1420,
    taluka: 'Dholera',
    centerSurvey: 128,
    totalSurveysApprox: 1420,
  },
  { 
    slug: 'bhadana', 
    name: 'Bhadana', 
    scheme: 'TP 1', 
    zone: 'Educational & University Zone',
    lat: 22.2582,
    lng: 72.2451,
    taluka: 'Dhandhuka',
    centerSurvey: 45,
    totalSurveysApprox: 890,
  },
  { 
    slug: 'bhadiyad', 
    name: 'Bhadiyad', 
    scheme: 'TP 1', 
    zone: 'High Access Mixed',
    lat: 22.2284,
    lng: 72.2536,
    taluka: 'Dholera',
    centerSurvey: 110,
    totalSurveysApprox: 1150,
  },
  { 
    slug: 'bhangadh', 
    name: 'Bhangadh', 
    scheme: 'TP 6', 
    zone: 'Solar Park & Clean Tech',
    lat: 22.0520,
    lng: 72.1534,
    taluka: 'Dholera',
    centerSurvey: 80,
    totalSurveysApprox: 1680,
  },
  { 
    slug: 'bhimnath', 
    name: 'Bhimnath', 
    scheme: 'TP 2', 
    zone: 'Rail Terminal & Industrial Core',
    lat: 22.3015,
    lng: 72.1382,
    taluka: 'Dhandhuka',
    centerSurvey: 99,
    totalSurveysApprox: 920,
  },
  { 
    slug: 'bhimtalav', 
    name: 'Bhimtalav', 
    scheme: 'TP 1', 
    zone: 'Renewable Hub',
    lat: 22.2380,
    lng: 72.2721,
    taluka: 'Dholera',
    centerSurvey: 64,
    totalSurveysApprox: 680,
  },
  { 
    slug: 'cher', 
    name: 'Cher', 
    scheme: 'TP 3', 
    zone: 'Waterfront & Coastal Tourism',
    lat: 22.2215,
    lng: 72.1754,
    taluka: 'Dholera',
    centerSurvey: 56,
    totalSurveysApprox: 760,
  },
  { 
    slug: 'dholera', 
    name: 'Dholera', 
    scheme: 'TP 3', 
    zone: 'City Center Commercial',
    lat: 22.2492,
    lng: 72.1932,
    taluka: 'Dholera',
    centerSurvey: 101,
    totalSurveysApprox: 2450,
  },
  { 
    slug: 'gogla', 
    name: 'Gogla', 
    scheme: 'TP 1', 
    zone: 'Residential & Civic',
    lat: 22.2185,
    lng: 72.2384,
    taluka: 'Dholera',
    centerSurvey: 60,
    totalSurveysApprox: 820,
  },
  { 
    slug: 'gorasu', 
    name: 'Gorasu', 
    scheme: 'TP 2', 
    zone: 'Heavy Industrial & Tech Parks',
    lat: 22.2743,
    lng: 72.2012,
    taluka: 'Dhandhuka',
    centerSurvey: 302,
    totalSurveysApprox: 1340,
  },
  { 
    slug: 'hebatpur', 
    name: 'Hebatpur', 
    scheme: 'TP 2', 
    zone: 'Semiconductor Fab Corridor',
    lat: 22.2851,
    lng: 72.1553,
    taluka: 'Dhandhuka',
    centerSurvey: 1122,
    totalSurveysApprox: 9432,
  },
  { 
    slug: 'kadipur', 
    name: 'Kadipur', 
    scheme: 'TP 1', 
    zone: 'Activation Industrial',
    lat: 22.2120,
    lng: 72.2245,
    taluka: 'Dholera',
    centerSurvey: 15,
    totalSurveysApprox: 1950,
  },
  { 
    slug: 'khun', 
    name: 'Khun', 
    scheme: 'TP 1', 
    zone: 'Coastal Heavy Industry',
    lat: 22.1852,
    lng: 72.2654,
    taluka: 'Dholera',
    centerSurvey: 48,
    totalSurveysApprox: 610,
  },
  { 
    slug: 'mundi', 
    name: 'Mundi', 
    scheme: 'TP 4', 
    zone: 'Logistics Corridor',
    lat: 22.3154,
    lng: 72.2281,
    taluka: 'Dhandhuka',
    centerSurvey: 78,
    totalSurveysApprox: 1210,
  },
  { 
    slug: 'otariya', 
    name: 'Otariya', 
    scheme: 'TP 2 / TP 3', 
    zone: 'High Access Commercial Corridor',
    lat: 22.2612,
    lng: 72.1691,
    taluka: 'Dhandhuka',
    centerSurvey: 65,
    totalSurveysApprox: 1520,
  },
  { 
    slug: 'panchi', 
    name: 'Panchi', 
    scheme: 'TP 2 / TP 4', 
    zone: 'Knowledge & High Access',
    lat: 22.3125,
    lng: 72.1824,
    taluka: 'Dhandhuka',
    centerSurvey: 38,
    totalSurveysApprox: 1180,
  },
  { 
    slug: 'pipli', 
    name: 'Pipli', 
    scheme: 'TP 2 / TP 4', 
    zone: 'Expressway Interchange Hub',
    lat: 22.3284,
    lng: 72.1725,
    taluka: 'Dhandhuka',
    centerSurvey: 85,
    totalSurveysApprox: 1730,
  },
  { 
    slug: 'rahtalav', 
    name: 'Rahtalav', 
    scheme: 'TP 2 / TP 4', 
    zone: 'Residential & Green Conservation',
    lat: 22.2981,
    lng: 72.2085,
    taluka: 'Dhandhuka',
    centerSurvey: 58,
    totalSurveysApprox: 1090,
  },
  { 
    slug: 'sandhida', 
    name: 'Sandhida', 
    scheme: 'TP 3 / TP 4', 
    zone: 'Knowledge & High Access',
    lat: 22.2682,
    lng: 72.1865,
    taluka: 'Dhandhuka',
    centerSurvey: 72,
    totalSurveysApprox: 980,
  },
  { 
    slug: 'sangasar', 
    name: 'Sangasar', 
    scheme: 'TP 3', 
    zone: 'Aerotropolis Cargo Support',
    lat: 22.2354,
    lng: 72.1623,
    taluka: 'Dholera',
    centerSurvey: 52,
    totalSurveysApprox: 870,
  },
  { 
    slug: 'umargadh', 
    name: 'Umargadh', 
    scheme: 'TP 1', 
    zone: 'Aviation MRO',
    lat: 22.2052,
    lng: 72.2521,
    taluka: 'Dholera',
    centerSurvey: 62,
    totalSurveysApprox: 640,
  },
  { 
    slug: 'zankhi', 
    name: 'Zankhi', 
    scheme: 'TP 6', 
    zone: 'Airport Logistics',
    lat: 22.0724,
    lng: 72.1783,
    taluka: 'Dholera',
    centerSurvey: 485,
    totalSurveysApprox: 2100,
  },
];

export const GAZETTED_SURVEYS = [
  101, 102, 105, 120, 145, 180, 204, 250, 320, 350, 399, 412, 450, 500, 550, 600, 650, 700,
];
